### ISSUE TITLE
Add support for secured and signed communications between nodes.

### ISSUE THREAD

**Issue by rgismondi** [GioAc96/Dollynator#25]
Add RSA encryption to messaging system for gossiping protocol.

**Comment by GioAc96** [comment]
The intent of this feature is to make communications between nodes secured and signed, in order to prevent nodes executing malicious commands coming from outside the botnet.
The feature makes use of the following cryptography principles:

- RSA asymmetric encryption is used to sign messages between nodes. Upon receiving a message, each node is able to verify the source of the message
- RSA asymmetric encryption is also used to share an AES key for symmetric encryption. The shared key is used to efficiently encrypt and decrypt the contents of the messages on the network
